### ISSUE TITLE
No module named src

### ISSUE THREAD

**Issue by 1140325971** [hwwang55/GraphGAN#19]
为什么我运行时会报这个错误呢？
Traceback (most recent call last):
  File "graph_gan.py", line 11, in <module>
    from src import utils
ModuleNotFoundError: No module named 'src'

**Comment by SRL94** [comment]
@1140325971 你解决了吗？

**Comment by shuo-git** [comment]
export PYTHONPATH=<The path of GraphGAN>:$PYTHONPATH
Adding your code dir to PYTHONPATH may help

**Comment by 915914082** [comment]
同问。。。楼主怎么解决的？

**Comment by Diamond0728** [comment]
> @1140325971 I solve this issue by running it in Pycharm.

It do works

**Comment by Diamond0728** [comment]
> @1140325971 I solve this issue by running it in Pycharm.

It works , thanks

**Comment by SherylHYX** [comment]
You can add these two lines at the beginning of graph_gan.py(可以考虑在graph_gan.py前面加上两行)：
import sys
sys.append.path("../../")

> 为什么我运行时会报这个错误呢？
> Traceback (most recent call last):
> File "graph_gan.py", line 11, in
> from src import utils
> ModuleNotFoundError: No module named 'src'

**Comment by liuhuofighting** [comment]
I use ubuntu20.04
import sys
sys.path.append("src所在的目录")   #可以在src目录下使用pwd查看
import utils
from evaluation import link_prediction as lp
import discriminator       #源代码缺少这个的引用
